### ISSUE TITLE
Boat Attack water system not working with 2020.2.0f1

### ISSUE THREAD

**Issue by luminati** [Unity-Technologies/BoatAttack#133]
Boat Attack water system not working in 2020.2.0f1. 

Shader error in 'hidden/preview/Multiply_28e22ddc9c0569868ba3f7659fecde8f': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/Multiply_7a1c4d936691708cb77d2bc0f33de411': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/Power_2f6846b0fc8bd08da018453b1aca0fbd': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/DotProduct_392bcf093de4738784e2931cc5705aa6': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/CustomFunction_493f8a0e3ada888680f0053c0ed04191': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/Multiply_485f43d8c662d28f8d10107cd62df47f': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/Remap_68c982ff473f0b8d83ca417d70fca973': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/CustomFunction_8ccc3e3964e1e78ca276bfff3e9b208e': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'hidden/preview/Add_63131ab1e469f185aea50fbadbef3f8b': Invalid conditional expression. at Assets/Shaders/CustomLighting.hlsl(5)

Shader error in 'BoatAttack/LWVegetationShader': 'InitializeStandardLitSurfaceData': output parameter 'outSurfaceData' not completely initialized at Assets/Shaders/Vegetation/InputSurfaceVegetation.hlsl(15) (on d3d11)

Shader error in 'BoatAttack/Water': redefinition of 'SurfaceData' at Copy/Library/PackageCache/com.unity.render-pipelines.universal@10.2.2/ShaderLibrary/SurfaceData.hlsl(5) (on d3d11)

**Comment by antont** [comment]
Maybe fixed?

Works at least in 2020.3 LTS and there is an upgrade commit, doesnt mention this but has shader changes, https://github.com/Unity-Technologies/BoatAttack/commit/8f74fa9c594ee8c73e5ffddf992842173355f405

**Comment by ADOHI** [comment]
same problems in 2020.3 LTS :(

**Comment by kirillich2019** [comment]
Go to YourProject\Packages\manifest.json and change the version of the package "com.unity.render-pipeline.universal" manually to the version below (for example 10.6.0 -> 10.5.0, I generally downgraded to 7); and wait for unity to update the packages. Somehow unity solves the problem of redefinition 'SurfaceData'.  Then you can roll back the URP version

**Comment by kirillich2019** [comment]
made it to work on version 2020.3.17f1.
I had to comment out the code in file WaterInput.hlsl in line 37
`/*struct SurfaceData
{
    half3 absorption;
	half3 scattering;
    half3 normal;
    half  foam;
};*/`

and replace the "InitializeBRDFData" method call in the "WaterCommon.hlsl" in line 248 
` InitializeBRDFData(half3(0, 0, 0), 0, half3(1, 1, 1), 0.9, 1, brdfData);
====>
float inoutAlpha = 1.0;
InitializeBRDFData(half3(0, 0, 0), 0, half3(1, 1, 1), 0.9, inoutAlpha, brdfData);`
