### ISSUE TITLE
How to use in 2019.3

### ISSUE THREAD

**Issue by klauskobald** [Unity-Technologies/BoatAttack#62]
I get shadergraph errors and packagemanager did not show shadergraph in the project.
So I added
    "com.unity.shadergraph": "7.1.1",
to the manifast.json

after reload unity till throws errors:

Library/PackageCache/com.unity.shadergraph@7.1.1/Editor/CodeGen/GraphCompilationResult.cs(5,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)

I am using 2019.3.0b9.
any ideas?

**Comment by klauskobald** [comment]
It works with 2019.3.0f5 - GREAT!
